---

- name: Deploy
  hosts:
  - tag_Name_reducto-frontend-01
  user: ubuntu
  sudo: true
  gather_facts: true
  tasks:
      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/

      - name: Run Akka
        command: /usr/local/reducto-dist/bin/start com.winston.api.ApiBoot
