---

- name: Re-deploy Single
  hosts:
  - tag_Name_reducto-01
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Kill previous run
        command: killall java
        ignore_errors: yes

      - name: Copy project Dist
        copy: src=../target/reducto-dist dest=/usr/local/

      - name: Run Frontend
        command: nohup /usr/local/reducto-dist/bin/start com.winston.api.ApiBoot &
        async: 450000
        poll: 0

      - name: Run Backend 1
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 2
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 3
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 4
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 5
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 6
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 7
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 8
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0          

      - name: Run Backend 9
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 10
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 11
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  

      - name: Run Backend 12
        command: nohup /usr/local/reducto-dist/bin/start com.winston.nlp.bootstrap.BackendDaemon &
        async: 450000
        poll: 0  